# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
use = ""

# : }}}

# : Manager {{{

[manager]
cwd = { fg = "cyan" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightcyan",   bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "white", bg = "green" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "yellow" }

# Border
border_symbol = "│"
border_style  = { fg = "gray" }

# Highlighting
syntect_theme = ""

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "gray", bg = "gray" }

# Mode
mode_normal = { bg = "blue", bold = true }
mode_select = { bg = "red", bold = true }
mode_unset  = { bg = "red", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

# Permissions
permissions_t = { fg = "green" }
permissions_r = { fg = "yellow" }
permissions_w = { fg = "red" }
permissions_x = { fg = "cyan" }
permissions_s = { fg = "darkgray" }

# : }}}


# : Select {{{

[select]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border   = { fg = "blue" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", underline = true }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "lightmagenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Help {{{

[help]
on      = { fg = "cyan" }
run     = { fg = "magenta" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "white" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
    # { mime = "image/*", fg = "cyan" },

	# Media
    # { mime = "{audio,video}/*", fg = "yellow" },

	# Archives
    # { mime = "application/*zip", fg = "magenta" },
    # { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "magenta" },

	# Documents
    # { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "green" },

	# Fallback
	{ name = "*", fg = "white" },
	{ name = "*/", fg = "blue" }
]

[icon]

dirs = [
    # Directory icons
    { name = ".config"    , text = "" },
    { name = ".git"       , text = "" },
    { name = "Desktop"    , text = "" },
    { name = "Development", text = "" },
    { name = "Documents"  , text = "" },
    { name = "Downloads"  , text = "" },
    { name = "Library"    , text = "" },
    { name = "Movies"     , text = "󰎁" },
    { name = "Music"      , text = "" },
    { name = "Pictures"   , text = "" },
    { name = "Public"     , text = "" },
    { name = "Videos"     , text = "󰎁" },
]
exts = [
    # Missing
    ## Programming
    { name = "py", text = "", fg_dark = "#ffbc03", fg_light = "#ffbc03" },
    { name = "go", text = "", fg_dark = "#519aba", fg_light = "#519aba" },
    { name = "rs", text = "", fg_dark = "#dea584", fg_light = "#dea584" },
    { name = "toml", text = "", fg_dark = "#9c4221", fg_light = "#9c4221" },
    { name = "md", text = "", fg_dark = "#dddddd", fg_light = "#dddddd" },
    { name = "css", text = "", fg_dark = "#42a5f5", fg_light = "#42a5f5" },
    { name = "svelte", text = "", fg_dark = "#ff3e00", fg_light = "#ff3e00" },
    { name = "html", text = "", fg_dark = "#e44d26", fg_light = "#e44d26" },
    { name = "sql", text = "", fg_dark = "#dad8d8", fg_light = "#dad8d8" },
    { name = "lock", text = "", fg_dark = "#bbbbbb", fg_light = "#bbbbbb" },
    { name = "lockb", text = "", fg_dark = "#bbbbbb", fg_light = "#bbbbbb" },
    ## Documents
    { name = "txt", text = "󰈙", fg_dark = "#89e051", fg_light = "#89e051" },
    { name = "pdf", text = "", fg_dark = "#b30b00", fg_light = "#b30b00" },
    ## Archives
    { name = "zip", text = "", fg_dark = "#eca517", fg_light = "#eca517" },
    { name = "7z", text = "", fg_dark = "#eca517", fg_light = "#eca517" },
    { name = "rar", text = "", fg_dark = "#eca517", fg_light = "#eca517" },
    ## Media
    { name = "svg", text = "󰜡", fg_dark = "#ffb13b", fg_light = "#ffb13b" },
    { name = "jpg", text = "", fg_dark = "#a074c4", fg_light = "#a074c4" },
    { name = "jpeg", text = "", fg_dark = "#a074c4", fg_light = "#a074c4" },
    { name = "png", text = "", fg_dark = "#a074c4", fg_light = "#a074c4" },
    { name = "webp", text = "", fg_dark = "#a074c4", fg_light = "#a074c4" },
    { name = "mp3", text = "", fg_dark = "#00afff", fg_light = "#00afff" },
    { name = "m4a", text = "", fg_dark = "#00afff", fg_light = "#00afff" },
    { name = "wav", text = "", fg_dark = "#00afff", fg_light = "#00afff" },
    { name = "flac", text = "", fg_dark = "#00afff", fg_light = "#00afff" },

    # DevIcons overrides
    { name = "json", text = "", fg_dark = "#dddddd", fg_light = "#dddddd" },
    { name = "json5", text = "", fg_dark = "#dddddd", fg_light = "#dddddd" },
    { name = "jsonc", text = "", fg_dark = "#dddddd", fg_light = "#dddddd" },
    { name = "js", text = "", fg_dark = "#F1F134", fg_light = "#F1F134" },
    { name = "ts", text = "", fg_dark = "#519aba", fg_light = "#519aba" },
    { name = "mp4", text = "", fg_dark = "#fd971f", fg_light = "#fd971f" },
    { name = "m4v", text = "", fg_dark = "#fd971f", fg_light = "#fd971f" },
    { name = "mov", text = "", fg_dark = "#fd971f", fg_light = "#fd971f" },
    { name = "mkv", text = "", fg_dark = "#fd971f", fg_light = "#fd971f" },
    { name = "webm", text = "", fg_dark = "#fd971f", fg_light = "#fd971f" },
]

# : }}}
